export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// PROFILE TYPES
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

// POST TYPES
export const GET_ALL_NOTAMS = 'GET_ALL_NOTAMS';
export const GET_UNREAD_NOTAMS = 'GET_UNREAD_NOTAMS';
export const CLEAR_CURRENT_NOTAMS = 'CLEAR_CURRENT_NOTAMS';

// EVENT TYPES
export const EVENTS_LOADING = 'EVENTS_LOADING';
export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const GET_EVENT = 'GET_EVENT';

// MISSION TYPES
export const MISSIONS_LOADING = 'MISSIONS_LOADING';
export const GET_ALL_MISSIONS = 'GET_ALL_MISSIONS';
export const GET_MISSION = 'GET_MISSION';

// DATA TYPES
export const DATA_LOADING = 'DATA_LOADING';
export const GET_AIRFIELDS = 'GET_AIRFIELDS';

// STATICS TYPES
export const GET_ALL_FRONTPAGESLIDERS = 'GET_ALL_FRONTPAGESLIDERS';

// DOCS TYPES
export const GET_ALL_ENDPOINTS = 'GET_ALL_ENDPOINTS';
