/**
 * Default Data-object for a MDC to use as default values when generating an MDC
 * It is important that each key/value pair has a value of either int, string or an array of objects!
 */
const defaultData = {
  date: '241900ZFEB2019',
  missionNumber: 'AI0112',
  callsign: 'JEDI-5',
  ato:
    'VTASK/132vW/20112/241900ZFEB2019//TASKUNIT/ 494th/ICAO:UGKO//AMSNDAT / AI0112 / AI / -/-/2 / -/-/DEPLOC: UGKO / ARRLOC: UGKO// MSNACFT / 4 / F / A - 18C / JEDI51 - 54 / -/-/CORAL9 / YELLOW11//',
  atis: ' - UNKNOWN - ',
  enr: 'DEP via AKAKI, AAR at SHELL, RTB via OHB',
  etd: '20:00:00Z',
  eta: '+2hrs',
  airfields: [
    {
      name: 'departure',
      id: 1,
      label: 'DEP',
      icao: 'UGKO',
      tcn: '44X',
      gnd: '134.100',
      twr: '134.200',
      elev: '68 ft',
      rwy: '08',
      ils: '109.750',
      lat: 42.177616666,
      lon: 42.48123,
    },
    {
      name: 'recovery',
      id: 59,
      label: 'ARR',
      icao: 'UGTB',
      tcn: '25X',
      gnd: '138.100',
      twr: '138.200',
      elev: '121 ft',
      rwy: '13R',
      ils: '110.300',
      lat: 42.177616666,
      lon: 42.48123,
    },
    {
      name: 'alternate',
      id: 1,
      label: 'ALTN',
      icao: 'UGKO',
      tcn: '44X',
      gnd: '132.100',
      twr: '132.200',
      elev: '88 ft',
      rwy: '09',
      ils: '108.900',
      lat: 42.177616666,
      lon: 42.48123,
    },
  ],
  aircraft: {
    id: 1,
    type: 'A-10C',
    nato: 'Warthog',
    role: 'cas',
  },
  element: [
    {
      pilot: 'NECK',
      tcn: '34X',
      laser: '1680',
      mode: '4231',
    },
    {
      pilot: 'WORG',
      tcn: '97X',
      laser: '1681',
      mode: '4232',
    },
    {
      pilot: 'DEX',
      tcn: '97X',
      laser: '1682',
      mode: '4233',
    },
    {
      pilot: 'FLAMINSQUIRREL',
      tcn: '97X',
      laser: '1683',
      mode: '4234',
    },
  ],
  navSequences: [{ sequence: '0-1-2-3-4-5-6' }, { sequence: '' }, { sequence: '' }],
  navPoints: [],
  radioPresets: [
    { label: 'INT PRI', preset: 'PRI5' },
    { label: 'INT AUX', preset: '125.750' },
    { label: 'GND', preset: 'AUX1' },
    { label: 'TWR:', preset: 'AUX2' },
    { label: 'CTRL', preset: 'AUX3' },
    { label: 'PACKG', preset: 'AUX10' },
    { label: 'TANK 1', preset: 'PRI7' },
    { label: 'TANK 2', preset: ' - ' },
    { label: 'AWACS', preset: 'AUX4' },
    { label: 'MAGIC', preset: 'AUX5' },
    { label: 'SCAR', preset: 'AUX15' },
    { label: 'CSAR', preset: 'AUX19' },
    { label: 'CAS1', preset: 'AUX13' },
    { label: 'CAS2', preset: 'AUX14' },
    { label: 'REPORT', preset: 'AUX8' },
    { label: 'ALERT', preset: 'AUX7' },
  ],
  packageName: 'Alpha',
  packageMembers: [
    {
      callsign: 'JEDI-5',
      numberOfAC: 4,
      ACtype: 'F/A-18C',
      uhf: 'CORAL9',
      vhf: ' - ',
      tcn: '34X/97X',
      tasking: 'AI',
    },
    {
      callsign: 'HAWK-3',
      numberOfAC: 2,
      ACtype: 'F/A-18C',
      uhf: 'LIME8',
      vhf: ' - ',
      tcn: '23X/86X',
      tasking: 'SEAD',
    },
    {
      callsign: 'RAVEN-6',
      numberOfAC: 2,
      ACtype: 'F/A-18C',
      uhf: 'OCHRE1',
      vhf: ' - ',
      tcn: '',
      tasking: 'CAP',
    },
    {
      callsign: '',
      numberOfAC: 0,
      ACtype: 'N/A',
      uhf: '000.000',
      vhf: '000.000',
      tcn: '',
      tasking: '',
    },
    {
      callsign: '',
      numberOfAC: 0,
      ACtype: 'N/A',
      uhf: '000.000',
      vhf: '000.000',
      tcn: '',
      tasking: '',
    },
  ],
  ta: 7000,
  tl: 180,
};

export default defaultData;
